/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emprob;

/**
 *
 * @author LuisMa
 */
public class submenu_Problemas extends javax.swing.JFrame {

    /**
     * Creates new form submenu_Problemas
     */
    public submenu_Problemas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloProblemas = new javax.swing.JTextField();
        SubtituloProblemas = new javax.swing.JTextField();
        TextoIDProblema = new javax.swing.JTextField();
        TextoNombreProblema = new javax.swing.JTextField();
        TextoDescripcion = new javax.swing.JTextField();
        TextoSolucion = new javax.swing.JTextField();
        IDProblema = new javax.swing.JTextField();
        NombreProblema = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        Solucion = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        menuProblemas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloProblemas.setEditable(false);
        TituloProblemas.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        TituloProblemas.setText("PROBLEMAS");
        TituloProblemas.setBorder(null);
        getContentPane().add(TituloProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 52, -1, 40));

        SubtituloProblemas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SubtituloProblemas.setText("Ingresa los datos:");
        SubtituloProblemas.setBorder(null);
        getContentPane().add(SubtituloProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        TextoIDProblema.setEditable(false);
        TextoIDProblema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoIDProblema.setText("ID Problema:");
        TextoIDProblema.setBorder(null);
        getContentPane().add(TextoIDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        TextoNombreProblema.setEditable(false);
        TextoNombreProblema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoNombreProblema.setText("Nombre del Problema:");
        TextoNombreProblema.setBorder(null);
        getContentPane().add(TextoNombreProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        TextoDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoDescripcion.setText("Descripcion:");
        TextoDescripcion.setBorder(null);
        getContentPane().add(TextoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        TextoSolucion.setEditable(false);
        TextoSolucion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoSolucion.setText("Solucion sugerida:");
        TextoSolucion.setBorder(null);
        TextoSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoSolucionActionPerformed(evt);
            }
        });
        getContentPane().add(TextoSolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));
        getContentPane().add(IDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, -1));
        getContentPane().add(NombreProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));

        Descripcion.setText("\n");
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 170, 80));
        getContentPane().add(Solucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 80));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 50, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regreso.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 50, 50));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        save.setBorderPainted(false);
        save.setContentAreaFilled(false);
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 60, 50));

        menuProblemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSUB_opt.jpg"))); // NOI18N
        getContentPane().add(menuProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoSolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoSolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(submenu_Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(submenu_Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(submenu_Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(submenu_Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new submenu_Problemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField IDProblema;
    private javax.swing.JTextField NombreProblema;
    private javax.swing.JTextField Solucion;
    private javax.swing.JTextField SubtituloProblemas;
    private javax.swing.JTextField TextoDescripcion;
    private javax.swing.JTextField TextoIDProblema;
    private javax.swing.JTextField TextoNombreProblema;
    private javax.swing.JTextField TextoSolucion;
    private javax.swing.JTextField TituloProblemas;
    private javax.swing.JButton back;
    private javax.swing.JLabel menuProblemas;
    private javax.swing.JButton salir;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
