/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emprob;

import manejoBD.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LuisMa
 */
public class submenu_Problemas extends javax.swing.JFrame {

    /**
     * Creates new form submenu_Problemas
     */
    private String nombreP, desc, soluS;
    private int iDP;
    
    public submenu_Problemas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloProblemas = new javax.swing.JTextField();
        SubtituloProblemas = new javax.swing.JTextField();
        TextoIDProblema = new javax.swing.JTextField();
        TextoNombreProblema = new javax.swing.JTextField();
        TextoDescripcion = new javax.swing.JTextField();
        TextoSolucion = new javax.swing.JTextField();
        IDProblema = new javax.swing.JTextField();
        NombreProblema = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        Solucion = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        menuProblemas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloProblemas.setEditable(false);
        TituloProblemas.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        TituloProblemas.setText("PROBLEMAS");
        TituloProblemas.setBorder(null);
        getContentPane().add(TituloProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 52, -1, 40));

        SubtituloProblemas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SubtituloProblemas.setText("Ingresa los datos:");
        SubtituloProblemas.setBorder(null);
        getContentPane().add(SubtituloProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        TextoIDProblema.setEditable(false);
        TextoIDProblema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoIDProblema.setText("ID Problema:");
        TextoIDProblema.setBorder(null);
        getContentPane().add(TextoIDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        TextoNombreProblema.setEditable(false);
        TextoNombreProblema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoNombreProblema.setText("Nombre del Problema:");
        TextoNombreProblema.setBorder(null);
        getContentPane().add(TextoNombreProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        TextoDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoDescripcion.setText("Descripcion:");
        TextoDescripcion.setBorder(null);
        getContentPane().add(TextoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        TextoSolucion.setEditable(false);
        TextoSolucion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoSolucion.setText("Solucion sugerida:");
        TextoSolucion.setBorder(null);
        TextoSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoSolucionActionPerformed(evt);
            }
        });
        getContentPane().add(TextoSolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        IDProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(IDProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, -1));
        getContentPane().add(NombreProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));

        Descripcion.setText("\n");
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 170, 80));
        getContentPane().add(Solucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 80));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regreso.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 50, 50));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        save.setBorderPainted(false);
        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 60, 50));

        menuProblemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSUB_opt.jpg"))); // NOI18N
        getContentPane().add(menuProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoSolucionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextoSolucionActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2Problemas().setVisible(true);
            }
        });
            this.dispose();              
    }//GEN-LAST:event_backActionPerformed

    private void IDProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDProblemaActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_IDProblemaActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(NombreProblema.getText().equals("")||IDProblema.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tiene que ingresar el nombre y el ID del problema");
        }
        else{
         try{
            iDP = Integer.parseInt(IDProblema.getText());
        }catch(NumberFormatException  ex){
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos en los id");
        }
        nombreP = NombreProblema.getText();
        desc = Descripcion.getText();
        soluS = Solucion.getText();
        if(existeClave(iDP)){
            JOptionPane.showMessageDialog(null, "ID de problema ya existente");
        }
        else{
            try{
            Statement sql = Conexion.getConexion().createStatement();
            sql.executeUpdate("INSERT INTO Problema " + "VALUES ( " + iDP +", '" + nombreP + "' ,'" + desc + "', '" + soluS + "')" );
            JOptionPane.showMessageDialog(null, "Datos Guardados");
            IDProblema.setText(null);
            NombreProblema.setText(null);
            Descripcion.setText(null);
            Solucion.setText(null);
            } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
            }
        }   
        }
        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField IDProblema;
    private javax.swing.JTextField NombreProblema;
    private javax.swing.JTextField Solucion;
    private javax.swing.JTextField SubtituloProblemas;
    private javax.swing.JTextField TextoDescripcion;
    private javax.swing.JTextField TextoIDProblema;
    private javax.swing.JTextField TextoNombreProblema;
    private javax.swing.JTextField TextoSolucion;
    private javax.swing.JTextField TituloProblemas;
    private javax.swing.JButton back;
    private javax.swing.JLabel menuProblemas;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private boolean existeClave(int nombre){
        boolean existe = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conect = new Conexion();
        Connection con = conect.getConexion();
        String consulta = "SELECT ID_Problema FROM Problema WHERE ID_Problema = ?";
        try {
            ps = con.prepareStatement(consulta);
            ps.setInt(1, nombre);
            rs = ps.executeQuery();
            
            if(rs.next()){
               existe = true;
            }
            
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
            existe = false;
        }
        return existe;
    }
        
}//class
