
package eliminacionModificacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import manejoBD.Conexion;
import emprob.*;


public class modificarTiendas extends javax.swing.JFrame {

    int idT, idE, numCa;
    String tel, calle, col, muni, est, ide, numca;
    
    public modificarTiendas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TituloTiendas = new javax.swing.JTextField();
        subtituloTiendas = new javax.swing.JTextField();
        TextoID_Tienda = new javax.swing.JTextField();
        TextoIDEncargado = new javax.swing.JTextField();
        TextoTelefono = new javax.swing.JTextField();
        TextoCalle = new javax.swing.JTextField();
        TextoNumCalle = new javax.swing.JTextField();
        TextoColonia = new javax.swing.JTextField();
        TextoMunicipio = new javax.swing.JTextField();
        TextoEstado = new javax.swing.JTextField();
        ID_Tienda = new javax.swing.JTextField();
        ID_Encargado = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Calle = new javax.swing.JTextField();
        NumCalle = new javax.swing.JTextField();
        Colonia = new javax.swing.JTextField();
        Municipio = new javax.swing.JTextField();
        Estado = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        menusub = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloTiendas.setEditable(false);
        TituloTiendas.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        TituloTiendas.setText("TIENDAS");
        TituloTiendas.setBorder(null);
        TituloTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloTiendasActionPerformed(evt);
            }
        });
        getContentPane().add(TituloTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 180, 40));

        subtituloTiendas.setEditable(false);
        subtituloTiendas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        subtituloTiendas.setText("Ingresa los datos:");
        subtituloTiendas.setBorder(null);
        subtituloTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtituloTiendasActionPerformed(evt);
            }
        });
        getContentPane().add(subtituloTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 30));

        TextoID_Tienda.setEditable(false);
        TextoID_Tienda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoID_Tienda.setText("ID Tienda:");
        TextoID_Tienda.setBorder(null);
        TextoID_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoID_TiendaActionPerformed(evt);
            }
        });
        getContentPane().add(TextoID_Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        TextoIDEncargado.setEditable(false);
        TextoIDEncargado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoIDEncargado.setText("ID Encargado:");
        TextoIDEncargado.setBorder(null);
        getContentPane().add(TextoIDEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        TextoTelefono.setEditable(false);
        TextoTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoTelefono.setText("Teléfono:");
        TextoTelefono.setBorder(null);
        TextoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(TextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 20));

        TextoCalle.setEditable(false);
        TextoCalle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoCalle.setText("Calle:");
        TextoCalle.setBorder(null);
        getContentPane().add(TextoCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 40, -1));

        TextoNumCalle.setEditable(false);
        TextoNumCalle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoNumCalle.setText("Num. Calle:");
        TextoNumCalle.setBorder(null);
        getContentPane().add(TextoNumCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 20));

        TextoColonia.setEditable(false);
        TextoColonia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoColonia.setText("Colonia:");
        TextoColonia.setToolTipText("");
        TextoColonia.setBorder(null);
        getContentPane().add(TextoColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 50, -1));

        TextoMunicipio.setEditable(false);
        TextoMunicipio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoMunicipio.setText("Municipio:");
        TextoMunicipio.setBorder(null);
        TextoMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoMunicipioActionPerformed(evt);
            }
        });
        getContentPane().add(TextoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 60, -1));

        TextoEstado.setEditable(false);
        TextoEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextoEstado.setText("Estado:");
        TextoEstado.setToolTipText("");
        TextoEstado.setBorder(null);
        getContentPane().add(TextoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 20));
        getContentPane().add(ID_Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, -1));

        ID_Encargado.setEditable(false);
        getContentPane().add(ID_Encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, -1));

        Telefono.setEditable(false);
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, -1));

        Calle.setEditable(false);
        getContentPane().add(Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, -1));

        NumCalle.setEditable(false);
        getContentPane().add(NumCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, -1));

        Colonia.setEditable(false);
        getContentPane().add(Colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, -1));

        Municipio.setEditable(false);
        getContentPane().add(Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, -1));

        Estado.setEditable(false);
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regreso.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 50, 50));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        save.setBorderPainted(false);
        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 50, 50));

        menusub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSUB_opt.jpg"))); // NOI18N
        getContentPane().add(menusub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloTiendasActionPerformed

    private void subtituloTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtituloTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtituloTiendasActionPerformed

    private void TextoID_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoID_TiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoID_TiendaActionPerformed

    private void TextoMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoMunicipioActionPerformed

    private void TextoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTelefonoActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2Tiendas().setVisible(true);
            }
        });
            this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            idT = Integer.parseInt(ID_Tienda.getText());
        }catch(NumberFormatException  ex){
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos en los id");
        }
        if(existeClaveT(idT)){
            try {
                Statement sql = Conexion.getConexion().createStatement();
                ResultSet rs;
                rs= sql.executeQuery("SELECT * FROM Tiendas where ID_Tienda = " + idT);
                while(rs.next()){
                    idE = rs.getInt("ID_Encargado");
                    numCa = rs.getInt("Numero_Calle");
                    tel = rs.getString("Telefono_T");
                    calle = rs.getString("Calle");
                    col = rs.getString("Colonia");
                    muni = rs.getString("Municipio");
                    est = rs.getString("Estado");
                 }
                ide = Integer.toString(idE);
                numca = Integer.toString(numCa);
                ID_Encargado.setText(ide);
                NumCalle.setText(numca);
                Telefono.setText(tel);
                Calle.setText(calle);
                Colonia.setText(col);
                Municipio.setText(muni);
                Estado.setText(est);
                
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "La tienda con el Id ingresado no existe");
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Calle;
    private javax.swing.JTextField Colonia;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField ID_Encargado;
    private javax.swing.JTextField ID_Tienda;
    private javax.swing.JTextField Municipio;
    private javax.swing.JTextField NumCalle;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField TextoCalle;
    private javax.swing.JTextField TextoColonia;
    private javax.swing.JTextField TextoEstado;
    private javax.swing.JTextField TextoIDEncargado;
    private javax.swing.JTextField TextoID_Tienda;
    private javax.swing.JTextField TextoMunicipio;
    private javax.swing.JTextField TextoNumCalle;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JTextField TituloTiendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menusub;
    private javax.swing.JButton save;
    private javax.swing.JTextField subtituloTiendas;
    // End of variables declaration//GEN-END:variables

    private boolean existeClaveT(int idT){
        boolean existe = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conect = new Conexion();
        Connection con = conect.getConexion();
        String consulta = "SELECT ID_Tienda FROM Tiendas WHERE ID_Tienda = ?";
        try {
            ps = con.prepareStatement(consulta);
            ps.setInt(1, idT);
            rs = ps.executeQuery();
            
            if(rs.next()){
                existe = true;
            }
            
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
            existe = false;
        }
        return existe;
    }
}
